# Generated by Django 5.0.4 on 2024-04-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name...', max_length=120)),
                ('cook_time', models.PositiveIntegerField(default=0)),
                ('ingredients', models.CharField(default='', help_text='enter ingredient(s) separate by comma', max_length=500)),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
